# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb761bc7fc0ce564b7522b6fb9935dda216ae7c4f35ed94891f351b0d662501f39dc3869251961bd20bfd4b96775caf840f4443d8ca9529223c3dd833f8f9726

test:
  secret_key_base: a1b0fe2165e019f18aeec8085ae35708962ce371ce0191508a6d651fcb3b1925860e851ff7390667599de9632a0e7fe386e87f899cb7c2f0c28025f7f0a4fbdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
